apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-nfs-pv
spec:
  capacity:
    storage: 1Gi
  storageClassName: my-nfs-storage
  accessModes:
    - ReadWriteMany
  nfs:
    path: /home/rayan/projet_02/nfs
    server: 172.21.214.182
